#############################################################################
# Makefile for building: harbour-thakir
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  harbour-thakir.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -o Makefile harbour-thakir.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_LOCATION_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_DBUS_LIB -DQT_SENSORS_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/sailfishapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/sailfishapp -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtLocation -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtPositioning -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtSensors -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = harbour-thakir1.0.0
DISTDIR = /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/.tmp/harbour-thakir1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/share/harbour-thakir/lib
LIBS          = $(SUBLIBS) -lsailfishapp -pie -rdynamic -lmdeclarativecache5 -lQt5Multimedia -lQt5Location -lQt5Quick -lQt5Svg -lQt5Gui -lQt5Qml -lQt5Network -lQt5Positioning -lQt5DBus -lQt5Sensors -lfontconfig -lQt5Sql -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = :

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/prayertimes.cpp \
		src/geocoder.cpp \
		src/prayermanager.cpp \
		src/playbackcontroller.cpp \
		src/islamicevents.cpp \
		src/quranmanager.cpp moc_geocoder.cpp \
		moc_prayermanager.cpp \
		moc_playbackcontroller.cpp \
		moc_powerbuttonwatcher.cpp \
		moc_athannotification.cpp \
		moc_eventsviewstatus.cpp \
		moc_appdbusadaptor.cpp \
		moc_quranmanager.cpp
OBJECTS       = main.o \
		prayertimes.o \
		geocoder.o \
		prayermanager.o \
		playbackcontroller.o \
		islamicevents.o \
		quranmanager.o \
		moc_geocoder.o \
		moc_prayermanager.o \
		moc_playbackcontroller.o \
		moc_powerbuttonwatcher.o \
		moc_athannotification.o \
		moc_eventsviewstatus.o \
		moc_appdbusadaptor.o \
		moc_quranmanager.o
DIST          = sounds/Athkar/*.ogg \
		sounds/Athkar/*.mp3 \
		qml/harbour-thakir.qml \
		qml/pages/MainPage.qml \
		qml/pages/Athkar.qml \
		qml/pages/CitySearchPage.qml \
		qml/pages/CityMapPage.qml \
		qml/pages/FavoritesPage.qml \
		qml/pages/SaveFavoriteDialog.qml \
		qml/pages/SettingsPage.qml \
		qml/pages/AppearancePage.qml \
		qml/pages/LocationSettingsPage.qml \
		qml/pages/AlertSettingsPage.qml \
		qml/pages/SilentModeSettingsPage.qml \
		qml/pages/TimeAdjustmentsPage.qml \
		qml/pages/IslamicEventPage.qml \
		qml/pages/StopPage.qml \
		qml/pages/QiblaPage.qml \
		qml/pages/AboutPage.qml \
		qml/pages/QuranIndexPage.qml \
		qml/pages/QuranReaderPage.qml \
		qml/pages/QuranDownloadPage.qml \
		qml/pages/QuranTafsirPage.qml \
		qml/pages/QuranSearchStatsPage.qml \
		qml/pages/QuranListeningStatsPage.qml \
		qml/pages/Images/*.png \
		qml/Images/*.png \
		qml/pages/Images/*.jpg \
		qml/Images/*.jpg \
		qml/pages/Images/*.svg \
		qml/Images/*.svg \
		qml/icons/*.svg \
		qml/fonts/* \
		qml/cover/CoverPage.qml \
		/usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp_i18n.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/dbuscommon.pri \
		/usr/share/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		harbour-thakir.pro src/prayertimes.h \
		src/geocoder.h \
		src/prayermanager.h \
		src/playbackcontroller.h \
		src/settingshelper.h \
		src/powerbuttonwatcher.h \
		src/athannotification.h \
		src/silentmodehelper.h \
		src/eventsviewstatus.h \
		src/appdbusadaptor.h \
		src/islamicevents.h \
		src/quranmanager.h \
		src/quranpageimageprovider.h src/main.cpp \
		src/prayertimes.cpp \
		src/geocoder.cpp \
		src/prayermanager.cpp \
		src/playbackcontroller.cpp \
		src/islamicevents.cpp \
		src/quranmanager.cpp
QMAKE_TARGET  = harbour-thakir
DESTDIR       = 
TARGET        = harbour-thakir


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: harbour-thakir.pro /usr/share/qt5/mkspecs/linux-g++/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/sanitize.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp_i18n.prf \
		/usr/share/qt5/mkspecs/features/sailfishapp.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/qt.prf \
		/usr/share/qt5/mkspecs/features/resources.prf \
		/usr/share/qt5/mkspecs/features/moc.prf \
		/usr/share/qt5/mkspecs/features/dbuscommon.pri \
		/usr/share/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt5/mkspecs/features/unix/opengl.prf \
		/usr/share/qt5/mkspecs/features/unix/thread.prf \
		/usr/share/qt5/mkspecs/features/file_copies.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		harbour-thakir.pro \
		/usr/lib64/libQt5Multimedia.prl \
		/usr/lib64/libQt5Location.prl \
		/usr/lib64/libQt5Quick.prl \
		/usr/lib64/libQt5Svg.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Qml.prl \
		/usr/lib64/libQt5Network.prl \
		/usr/lib64/libQt5Positioning.prl \
		/usr/lib64/libQt5DBus.prl \
		/usr/lib64/libQt5Sensors.prl \
		/usr/lib64/libQt5Sql.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -o Makefile harbour-thakir.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/sanitize.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmfmessageserver_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt5/mkspecs/features/sailfishapp_i18n.prf:
/usr/share/qt5/mkspecs/features/sailfishapp.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/qt.prf:
/usr/share/qt5/mkspecs/features/resources.prf:
/usr/share/qt5/mkspecs/features/moc.prf:
/usr/share/qt5/mkspecs/features/dbuscommon.pri:
/usr/share/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt5/mkspecs/features/dbusadaptors.prf:
/usr/share/qt5/mkspecs/features/unix/opengl.prf:
/usr/share/qt5/mkspecs/features/unix/thread.prf:
/usr/share/qt5/mkspecs/features/file_copies.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
harbour-thakir.pro:
/usr/lib64/libQt5Multimedia.prl:
/usr/lib64/libQt5Location.prl:
/usr/lib64/libQt5Quick.prl:
/usr/lib64/libQt5Svg.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Qml.prl:
/usr/lib64/libQt5Network.prl:
/usr/lib64/libQt5Positioning.prl:
/usr/lib64/libQt5DBus.prl:
/usr/lib64/libQt5Sensors.prl:
/usr/lib64/libQt5Sql.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) 'QMAKE_CFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_RELEASE=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' 'QMAKE_CXXFLAGS_DEBUG=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a' QMAKE_STRIP=: PREFIX=/usr LIBDIR=/usr/lib64 -o Makefile harbour-thakir.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/prayertimes.h src/geocoder.h src/prayermanager.h src/playbackcontroller.h src/settingshelper.h src/powerbuttonwatcher.h src/athannotification.h src/silentmodehelper.h src/eventsviewstatus.h src/appdbusadaptor.h src/islamicevents.h src/quranmanager.h src/quranpageimageprovider.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/prayertimes.cpp src/geocoder.cpp src/prayermanager.cpp src/playbackcontroller.cpp src/islamicevents.cpp src/quranmanager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents translations/harbour-thakir-ar.ts translations/harbour-thakir-tr.ts translations/harbour-thakir-fr.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_geocoder.cpp moc_prayermanager.cpp moc_playbackcontroller.cpp moc_powerbuttonwatcher.cpp moc_athannotification.cpp moc_eventsviewstatus.cpp moc_appdbusadaptor.cpp moc_quranmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_geocoder.cpp moc_prayermanager.cpp moc_playbackcontroller.cpp moc_powerbuttonwatcher.cpp moc_athannotification.cpp moc_eventsviewstatus.cpp moc_appdbusadaptor.cpp moc_quranmanager.cpp
moc_geocoder.cpp: src/geocoder.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/geocoder.h -o moc_geocoder.cpp

moc_prayermanager.cpp: src/prayertimes.h \
		src/geocoder.h \
		src/prayermanager.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/prayermanager.h -o moc_prayermanager.cpp

moc_playbackcontroller.cpp: src/playbackcontroller.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/playbackcontroller.h -o moc_playbackcontroller.cpp

moc_powerbuttonwatcher.cpp: src/powerbuttonwatcher.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/powerbuttonwatcher.h -o moc_powerbuttonwatcher.cpp

moc_athannotification.cpp: src/athannotification.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/athannotification.h -o moc_athannotification.cpp

moc_eventsviewstatus.cpp: src/settingshelper.h \
		src/eventsviewstatus.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/eventsviewstatus.h -o moc_eventsviewstatus.cpp

moc_appdbusadaptor.cpp: src/appdbusadaptor.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/appdbusadaptor.h -o moc_appdbusadaptor.cpp

moc_quranmanager.cpp: src/quranmanager.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/share/qt5/mkspecs/linux-g++ -I/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/sailfishapp -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0 -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/aarch64-meego-linux-gnu -I/opt/cross/aarch64-meego-linux-gnu/include/c++/13.4.0/backward -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include -I/usr/local/include -I/opt/cross/lib/gcc/aarch64-meego-linux-gnu/13.4.0/include-fixed -I/opt/cross/aarch64-meego-linux-gnu/include -I/usr/include src/quranmanager.h -o moc_quranmanager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/prayermanager.h \
		src/prayertimes.h \
		src/geocoder.h \
		src/playbackcontroller.h \
		src/settingshelper.h \
		src/powerbuttonwatcher.h \
		src/eventsviewstatus.h \
		src/athannotification.h \
		src/silentmodehelper.h \
		src/appdbusadaptor.h \
		src/quranmanager.h \
		src/quranpageimageprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

prayertimes.o: src/prayertimes.cpp src/prayertimes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prayertimes.o src/prayertimes.cpp

geocoder.o: src/geocoder.cpp src/geocoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geocoder.o src/geocoder.cpp

prayermanager.o: src/prayermanager.cpp src/prayermanager.h \
		src/prayertimes.h \
		src/geocoder.h \
		src/settingshelper.h \
		src/eventsviewstatus.h \
		src/islamicevents.h \
		src/silentmodehelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prayermanager.o src/prayermanager.cpp

playbackcontroller.o: src/playbackcontroller.cpp src/playbackcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playbackcontroller.o src/playbackcontroller.cpp

islamicevents.o: src/islamicevents.cpp src/islamicevents.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o islamicevents.o src/islamicevents.cpp

quranmanager.o: src/quranmanager.cpp src/quranmanager.h \
		src/settingshelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quranmanager.o src/quranmanager.cpp

moc_geocoder.o: moc_geocoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_geocoder.o moc_geocoder.cpp

moc_prayermanager.o: moc_prayermanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prayermanager.o moc_prayermanager.cpp

moc_playbackcontroller.o: moc_playbackcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playbackcontroller.o moc_playbackcontroller.cpp

moc_powerbuttonwatcher.o: moc_powerbuttonwatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_powerbuttonwatcher.o moc_powerbuttonwatcher.cpp

moc_athannotification.o: moc_athannotification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_athannotification.o moc_athannotification.cpp

moc_eventsviewstatus.o: moc_eventsviewstatus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventsviewstatus.o moc_eventsviewstatus.cpp

moc_appdbusadaptor.o: moc_appdbusadaptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appdbusadaptor.o moc_appdbusadaptor.cpp

moc_quranmanager.o: moc_quranmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quranmanager.o moc_quranmanager.cpp

####### Install

install_sounds: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/adhan_court.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/adhan_Maddina.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/adhan_Makka.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Beep.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/bip.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Fajr.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/

uninstall_sounds: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Fajr.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/bip.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Beep.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/adhan_Makka.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/adhan_Maddina.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/adhan_court.ogg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/ 


install_athkarsounds: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_10.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_13.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_14.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_17.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_18.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_19.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_3.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_4.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_6.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_8.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_15.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_4.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/3_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/3_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/5_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_10.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_13.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_14.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_17.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_18.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_19.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_3.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_4.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_6.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/1_8.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_15.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/2_4.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/3_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/3_2.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/sounds/Athkar/5_1.ogg $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/

uninstall_athkarsounds: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/5_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/3_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/3_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_4.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_15.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_8.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_6.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_4.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_3.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_19.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_18.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_17.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_14.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_13.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_10.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/5_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/3_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/3_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_4.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_15.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/2_1.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_8.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_6.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_4.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_3.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_2.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_19.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_18.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_17.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_14.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_13.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_10.ogg
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/1_1.ogg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/sounds/Athkar/ 


install_files: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/files || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/files
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/ara-quranuthmanihaf.min.json $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/ara-quranwarsh.min.json $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/Hikmato_El_Youm.txt $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/quran-simple-clean.xml $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/tanzil-quran-data.xml $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/warsh_quran_authentic.json $(INSTALL_ROOT)/usr/share/harbour-thakir/files/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/files/WarshLists.ts $(INSTALL_ROOT)/usr/share/harbour-thakir/files/

uninstall_files: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/WarshLists.ts
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/warsh_quran_authentic.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/tanzil-quran-data.xml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/quran-simple-clean.xml
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/Hikmato_El_Youm.txt
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/ara-quranwarsh.min.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/files/ara-quranuthmanihaf.min.json
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/files/ 


install_data: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/data || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/data
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/data/quran.db $(INSTALL_ROOT)/usr/share/harbour-thakir/data/

uninstall_data: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/data/quran.db
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/data/ 


install_quransvg: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir
	-$(INSTALL_DIR) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/quran_svg $(INSTALL_ROOT)/usr/share/harbour-thakir/

uninstall_quransvg: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/quran_svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/ 


install_translations: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/translations || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/translations
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-ar.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-fr.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-tr.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/

uninstall_translations: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-tr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-ar.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/ 


install_icon86: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/icons/86x86/apps/harbour-thakir.png $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/

uninstall_icon86: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/harbour-thakir.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/86x86/apps/ 


install_icon108: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/icons/108x108/apps/harbour-thakir.png $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/

uninstall_icon108: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/harbour-thakir.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/108x108/apps/ 


install_icon128: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/icons/128x128/apps/harbour-thakir.png $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/

uninstall_icon128: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/harbour-thakir.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 


install_icon172: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/icons/172x172/apps/harbour-thakir.png $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/

uninstall_icon172: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/harbour-thakir.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/172x172/apps/ 


install_checktimer: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/systemd/system || mkdir -p $(INSTALL_ROOT)/usr/lib/systemd/system
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/systemd/harbour-thakir-check.timer $(INSTALL_ROOT)/usr/lib/systemd/system/

uninstall_checktimer: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/systemd/system/harbour-thakir-check.timer
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/systemd/system/ 


install_checkservice: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/systemd/system || mkdir -p $(INSTALL_ROOT)/usr/lib/systemd/system
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/systemd/harbour-thakir-check.service $(INSTALL_ROOT)/usr/lib/systemd/system/

uninstall_checkservice: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/systemd/system/harbour-thakir-check.service
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/systemd/system/ 


install_dbusservice: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/dbus-1/services || mkdir -p $(INSTALL_ROOT)/usr/share/dbus-1/services
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/dbus/org.hafsoftdz.harbour-thakir.service $(INSTALL_ROOT)/usr/share/dbus-1/services/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/dbus/org.hafsoftdz.harbour_thakir.service $(INSTALL_ROOT)/usr/share/dbus-1/services/

uninstall_dbusservice: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/org.hafsoftdz.harbour_thakir.service
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/org.hafsoftdz.harbour-thakir.service
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 


install_qm: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir/translations || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir/translations
	lupdate -noobsolete /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/src /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/qml -ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-ar.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-tr.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-fr.ts && mkdir -p translations && [ "/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir" != "/c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir" -a 1 -eq 1 ] && cp -af /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-ar.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-tr.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-fr.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations || : ; [ 1 -eq 1 ] && lrelease -nounfinished /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-ar.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-tr.ts /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-fr.ts || :
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-ar.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-tr.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/translations/harbour-thakir-fr.qm $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/

uninstall_qm: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-tr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/harbour-thakir-ar.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/translations/ 


install_qml: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/harbour-thakir || mkdir -p $(INSTALL_ROOT)/usr/share/harbour-thakir
	-$(INSTALL_DIR) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/qml $(INSTALL_ROOT)/usr/share/harbour-thakir/

uninstall_qml: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/harbour-thakir/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/harbour-thakir/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	-$(INSTALL_FILE) /c/Users/hafte/.gemini/antigravity/scratch/harbour-thakir/harbour-thakir.desktop $(INSTALL_ROOT)/usr/share/applications/

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/harbour-thakir.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install: install_sounds install_athkarsounds install_files install_data install_quransvg install_translations install_icon86 install_icon108 install_icon128 install_icon172 install_checktimer install_checkservice install_dbusservice install_qm install_qml install_target install_desktop  FORCE

uninstall: uninstall_sounds uninstall_athkarsounds uninstall_files uninstall_data uninstall_quransvg uninstall_translations uninstall_icon86 uninstall_icon108 uninstall_icon128 uninstall_icon172 uninstall_checktimer uninstall_checkservice uninstall_dbusservice uninstall_qm uninstall_qml uninstall_target uninstall_desktop  FORCE

FORCE:

